changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Docs And Release
      labels:
        - chore
        - docs
        - documentation
        - release
